### ISSUE TITLE
Issues running samepage dev

### ISSUE THREAD

**Issue by mdroidian** [samepage-network/samepage.network#62]
Here's the first go, I'm stuck on the `mysql` step @dvargas92495 :

On Windows, so used WSL2 to `git clone` to handle `:` in folder names.
- `npm i`
- `npm start`
- Error: `ENOENT: no such file or directory, open '/home/michael/.ngrok2/ngrok.yml'`
- I just created one like this based on `start.ts`:
```
tunnels:
  dev:
    proto: http
    addr: 3000
    hostname: samepage.ngrok.io
  api:
    proto: http
    addr: 3003
    hostname: api.samepage.ngrok.io
```
- copied `.env.default` to `.env`
- added `CLERK_SECRET_KEY`
- installed `mysql`
- `CREATE USER 'samepage_network'@'localhost' IDENTIFIED BY 'samepage_network';`
- `GRANT ALL PRIVILEGES ON mysql.* TO 'samepage_network'@'localhost';`
- run `npx ts-node scripts/cli.ts plan --sql`
- error: 
```
No mysql schema queries to run!
Error: Table 'samepage_network._migrations' doesn't exist
```
